#######
# Cloudify Blueprint which describes the nodecellar application
# https://github.com/ccoenraets/nodecellar
#
imports:
     -  http://www.getcloudify.org/spec/cloudify/3.0/types.yaml

blueprint:
    name: nodecellar
    nodes:
        -   name: nodejs_vm
            type: cloudify.types.host
            properties:
                ip: 127.0.0.1
                cloudify_agent:
                    key: /home/vagrant/.ssh/cloudify_private_key
            
        -   name: mongod_vm
            type: cloudify.types.host
            properties:
                ip: 127.0.0.1
                cloudify_agent:
                    key: /home/vagrant/.ssh/cloudify_private_key
