#######
# Cloudify Blueprint which describes the nodecellar application
# https://github.com/ccoenraets/nodecellar
#
imports:
     - http://www.getcloudify.org/spec/cloudify/3.0/types.yaml
     - http://www.getcloudify.org/spec/cloudify/3.0/bash.yaml
     - nodecellar-config-plugin/plugin.yaml

types:
    mongo_database:
        derived_from: cloudify.types.bash.db_server
        properties:
            -   role
            -   port

    nodejs_server:
        derived_from: cloudify.types.bash.app_server

    nodejs_app:
        derived_from: cloudify.types.bash.app_module
        properties:
            -   app_name
            -   startup_script
            -   git_url
            -   git_branch
            -   base_port
            -   num_instances
            -   env_file_path

relationships:
    nodecellar_connected_to_mongo:
        derived_from: cloudify.relationships.connected_to
        source_interfaces:
            cloudify.interfaces.relationship_lifecycle:
                - postconfigure: nodecellar_config_plugin.tasks.get_mongo_host_and_port


    

blueprint:
    name: nodecellar
    -   name: nodejs_vm
            type: cloudify.types.host
            properties:
                    ip: 127.0.0.1
                    cloudify_agent:
                        key: /home/vagrant/.ssh/cloudify_private_key
            
        -   name: mongod_vm
            type: cloudify.types.host
            properties:
                    ip: 127.0.0.1
                    cloudify_agent:
                        key: /home/vagrant/.ssh/cloudify_private_key


        - name: mongod
          type: mongo_database
          properties:
                role: mongod
                port: 27017
                scripts:           
                    create: mongo-scripts/install-mongo.sh
                    start: mongo-scripts/start-mongo.sh
                    stop: mongo-scripts/stop-mongo.sh
          relationships:
            - target: mongod_vm
              type: cloudify.relationships.contained_in

        - name: nodejs
          type: nodejs_server
          properties:
                scripts:           
                    create: nodejs-scripts/install-nodejs.sh
          relationships:
            - type: cloudify.relationships.contained_in
              target: nodejs_vm

        - name: nodecellar_app
          type: nodejs_app
          properties:
                app_name: nodecellar
                startup_script: server.js
                git_url: https://github.com/uric/nodecellar.git
                git_branch: master
                base_port: 8080
                num_instances: 1
                env_file_path: /tmp/mongo_host_and_port.sh
                scripts:           
                    create: nodejs-scripts/install-app.sh
                    start: nodejs-scripts/start-app.sh
                    stop: nodejs-scripts/stop-app.sh
          relationships:
            - type: cloudify.relationships.contained_in
              target: nodejs
            - type: nodecellar_connected_to_mongo
              target: mongod  






